package Iterator;

import java.io.IOError;
import java.io.IOException;

public class Single_Try_Multiple_Catches {
	
	
	
  public static void main(String args[]) {
	  
	  
	  try
	  {
		  int a=9/0;
	  }
	  catch(Throwable b)
	  {
		  System.out.println("Excepetion is found by declaring as  Throwable interface");
		  
		  
	  }
	 
	  
	 
	  
  }

}
